coverage:
    precision: 1
    round: down
    range: "50...100"

    status:
        project:
            default:
                enabled: yes
                target: 0%
                threshold: null
        patch:
            default:
                enabled: yes
                target: 0%
                threshold: null

    ignore:
        - "versioneer.py"
        - "versioneer_extended.py"
