from matrix.constants import UNIVERSAL_PERMUTATION_METHODS, DECOMPOSITION_TYPES, NO_PERMUTATION_METHOD

CHOLMOD_NO_PERMUTATION_METHOD = 'natural'
try:
    import sksparse.cholmod
except ImportError:
    CHOLMOD_PERMUTATION_METHODS = ()
else:
    CHOLMOD_PERMUTATION_METHODS = tuple(sksparse.cholmod._ordering_methods.keys())
    assert 'best' in CHOLMOD_PERMUTATION_METHODS
    assert 'default' in CHOLMOD_PERMUTATION_METHODS
FILL_REDUCE_PERMUTATION_METHOD_PREFIX = 'fill_reduce_'
FILL_REDUCE_PERMUTATION_METHODS = tuple(FILL_REDUCE_PERMUTATION_METHOD_PREFIX + method for method in CHOLMOD_PERMUTATION_METHODS if method != CHOLMOD_NO_PERMUTATION_METHOD)
SPARSE_ONLY_PERMUTATION_METHODS = FILL_REDUCE_PERMUTATION_METHODS
""" Supported permutation methods only for sparse matrices. """

if len(CHOLMOD_PERMUTATION_METHODS) > 0:
    BEST_FILL_REDUCE_PERMUTATION_METHOD = FILL_REDUCE_PERMUTATION_METHOD_PREFIX + 'best'
    """ Supported permutation method to best reduce fill of decomposed sparse matrices. """
    DEFAULT_FILL_REDUCE_PERMUTATION_METHOD = FILL_REDUCE_PERMUTATION_METHOD_PREFIX + 'default'
    """ Supported permutation method to default reduce fill of decomposed sparse matrices. """
    assert BEST_FILL_REDUCE_PERMUTATION_METHOD in FILL_REDUCE_PERMUTATION_METHODS
    assert DEFAULT_FILL_REDUCE_PERMUTATION_METHOD in FILL_REDUCE_PERMUTATION_METHODS
else:
    BEST_FILL_REDUCE_PERMUTATION_METHOD = NO_PERMUTATION_METHOD
    DEFAULT_FILL_REDUCE_PERMUTATION_METHOD = NO_PERMUTATION_METHOD

PERMUTATION_METHODS = UNIVERSAL_PERMUTATION_METHODS + SPARSE_ONLY_PERMUTATION_METHODS
""" Supported permutation methods for decompose sparse matrices. """
