from matrix.constants import UNIVERSAL_PERMUTATION_METHODS, DECOMPOSITION_TYPES

CHOLMOD_NO_PERMUTATION_METHOD = 'natural'
try:
    import sksparse.cholmod
except ImportError:
    CHOLMOD_PERMUTATION_METHODS = ()
else:
    CHOLMOD_PERMUTATION_METHODS = tuple(sksparse.cholmod._ordering_methods.keys())
FILL_REDUCE_PERMUTATION_METHOD_PREFIX = 'fill_reduce_'
FILL_REDUCE_PERMUTATION_METHODS = tuple(FILL_REDUCE_PERMUTATION_METHOD_PREFIX + method for method in CHOLMOD_PERMUTATION_METHODS if method != CHOLMOD_NO_PERMUTATION_METHOD)
SPARSE_ONLY_PERMUTATION_METHODS = FILL_REDUCE_PERMUTATION_METHODS
""" Supported permutation methods only for sparse matrices. """

PERMUTATION_METHODS = UNIVERSAL_PERMUTATION_METHODS + SPARSE_ONLY_PERMUTATION_METHODS
